export const SHOW_LOADING_SCREEN = 'SHOW_LOADING_SCREEN';
export const HIDE_LOADING_SCREEN = 'HIDE_LOADING_SCREEN';

export const CHANGE_TAB = 'CHANGE_TAB';

export const SET_APOD_IMAGES = 'SET_APOD_IMAGES';
export const SHOW_APOD_ERROR = 'SHOW_APOD_ERROR';
export const HIDE_APOD_ERROR = 'HIDE_APOD_ERROR';

export const CHANGE_MONTH = 'CHANGE_MONTH';
export const CHANGE_YEAR = 'CHANGE_YEAR';
export const CHANGE_TYPE = 'CHANGE_TYPE';

export const SHOW_LIGHT_BOX = 'SHOW_LIGHT_BOX';
export const HIDE_LIGHT_BOX = 'HIDE_LIGHT_BOX';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const HIDE_TOAST = 'HIDE_TOAST';
export const SHOW_TOAST = 'SHOW_TOAST';

export const ORDER_FAVORITE_BY_DATE = 'ORDER_FAVORITE_BY_DATE';
export const ORDER_FAVORITE_BY_NAME = 'ORDER_FAVORITE_BY_NAME';
export const ORDER_FAVORITE_BY_TYPE = 'ORDER_FAVORITE_BY_TYPE';